apiVersion: v1
kind: Service
metadata:
  name: bendrocorp-frontend-service
  labels:
    app: bendrocorp-frontend-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: bendrocorp-frontend-deployment